name: Check with MATLAB
on:
  push:
  pull_request:
  workflow_dispatch: 
  
jobs:
  mlint:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2.3.4
        
      - name: Install MATLAB
        uses: matlab-actions/setup-matlab@v0.2.1
        with:
          release: R2020b
        
      - name: Run tests and generate artifacts
        uses: matlab-actions/run-command@v0.2.3
        with:
          command: cd SpringProject; rpt = mlintrpt; writecell(rpt, 'report.html', 'FileType', 'text')
  RC_Func_Sample:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2.3.4
       
      - name: Install MATLAB
        uses: matlab-actions/setup-matlab@v0.2.1
        with:
          release: R2020b
          
      - name: Run RC_Func_Test
        uses: matlab-actions/run-command@v.0.2.3
        with:
          command: cd SprintProject; RC_Func_Sample
        
