# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  RC_Func_Sample:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      
      - name: Checkout Code
        uses: actions/checkout@v2.3.4

      - name: Install Octave
        run: sudo apt install -y octave

      - name: Change to Correct SubDirectory
        run: cd SpringProject
        
      - name: Creater Dummy Coder Class
        run: printf "classdef coder\nmethods (Static)\nfunction x = ignoreConst(x)\nend\nend\nend" > coder.m 
        
      - name: Create wrapper for testing with octave
        run: printf "warning('off', 'Octave:divide-by-zero')\nRC_Func_Sample" > octave_test
        
      - name: Test that the function runs.
        run: octave --no-gui octave_test
